#!/bin/bash

python removeNewline.py $1 tmp1.fasta

sed 's/N//g' tmp1.fasta > tmp.fasta

time java TandemRepeatSearcher tmp.fasta | cut -d" " -f1 | awk '{s+=$1} END {print s}' 

echo 'Searching for Approx. Repeats'

time java TandemRepeatSearcherApprox tmp.fasta | cut -d" " -f1 | awk '{s+=$1} END {print s}' 

echo $1
echo 'Finished !!'
