#!/bin/sh

if [ -z $1 ]; then
    echo 'Usage: ./SCRIPT /path/to/dna_sequence'
    exit 1
fi

python removeNewline.py $1 data_t.fasta
java TandemRepeatFinderSeq data_t.fasta > freq.csv

# python plot.py
# mv per_freq.png $1.png
# mv per_len.png $1.png

echo $1
echo 'Finished !!'